### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by sunnystormy** [anael-seghezzi/Maratis-Tiny-C-library#3]
"[ 75%] Linking C executable RasterTest
/usr/bin/ld: CMakeFiles/RasterTest.dir/main.c.o: undefined reference to symbol 'fmodf@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
tests/raster/CMakeFiles/RasterTest.dir/build.make:87: recipe for target 'tests/raster/RasterTest' failed
make[2]: *** [tests/raster/RasterTest] Error 1
CMakeFiles/Makefile2:217: recipe for target 'tests/raster/CMakeFiles/RasterTest.dir/all' failed
make[1]: *** [tests/raster/CMakeFiles/RasterTest.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
[  6%] Built target tinycthread
[ 72%] Built target glfw
[ 75%] Linking C executable RasterTest
/usr/bin/ld: CMakeFiles/RasterTest.dir/main.c.o: undefined reference to symbol 'fmodf@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
tests/raster/CMakeFiles/RasterTest.dir/build.make:87: recipe for target 'tests/raster/RasterTest' failed
make[2]: *** [tests/raster/RasterTest] Error 1
CMakeFiles/Makefile2:217: recipe for target 'tests/raster/CMakeFiles/RasterTest.dir/all' failed
make[1]: *** [tests/raster/CMakeFiles/RasterTest.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
"

This is what I get when trying to build on my Debian "Buster" machine. Any ideas? Thank you!

**Comment by anael-seghezzi** [comment]
fmodf is normally part of math.h.
GLIBC reference may be missing in CMakeLists.txt, not sure if there is a debian specifics.

**Comment by sunnystormy** [comment]
My glibc version is 2.27... so maybe we need a way to update the build script?

**Comment by anael-seghezzi** [comment]
It should be fixed now

**Comment by sunnystormy** [comment]
@anael-seghezzi Builds fine now, thank you! :D
